server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/we/study_workspace/spring-cloud-config
          uri: https://github.com/robin00q/spring-cloud-config